@FreelanceOps.Api_HostAddress = http://localhost:5244

GET {{FreelanceOps.Api_HostAddress}}/health
Accept: application/json

###

GET {{FreelanceOps.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###

POST {{FreelanceOps.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "batuhan@example.com",
  "password": "Password123!",
  "fullName": "Batuhan Sac"
}

###

POST {{FreelanceOps.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "batuhan@example.com",
  "password": "Password123!"
}

###
